"""
ScotlandAI Navigator — API Router

All API endpoints in one place. The backend is deliberately simple:
- One endpoint to generate a brief (POST /generate-brief)
- One endpoint to download the PDF (GET /download/{token})
- One health check (GET /health)

WHY SO FEW ENDPOINTS:
The backend is stateless by design. The OpenClaw agent handles the conversation.
The backend only does what the agent cannot: call Gemini with a structured prompt,
validate the output, generate a PDF, and return a signed download link.

One POST in, one brief out. No sessions. No database. No complexity.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from fastapi.concurrency import run_in_threadpool
from itsdangerous import SignatureExpired, BadSignature

from core.config import settings
from core.security import generate_download_token, verify_download_token
from schemas.discovery import DiscoveryAnswers
from schemas.brief import APIBriefResponse
from services.brief_builder import generate_brief, extract_organisation_name
from services.pdf_generator import generate_pdf, save_pdf

logger = logging.getLogger(__name__)

router = APIRouter()

# Where generated PDFs are stored
BRIEFS_DIR = Path("static/briefs")
BRIEFS_DIR.mkdir(parents=True, exist_ok=True)


# ═══════════════════════════════════════════════
# POST /generate-brief — The main endpoint
# ═══════════════════════════════════════════════

@router.post(
    "/generate-brief",
    response_model=APIBriefResponse,
    summary="Generate an AI Opportunity Brief",
    description=(
        "Takes 5 validated discovery answers and produces a board-ready "
        "AI Opportunity Brief with 3 specific AI product recommendations, "
        "each mapped to DataVita infrastructure, plus a downloadable PDF."
    ),
    responses={
        200: {"description": "Brief generated successfully with PDF download link"},
        422: {"description": "Validation error — one or more answers failed validation"},
        500: {"description": "Brief generation failed — Gemini API error or retry exhaustion"},
    },
)
async def generate_brief_endpoint(
    answers: DiscoveryAnswers,
    background_tasks: BackgroundTasks,
):
    """
    The complete brief generation pipeline:
    1. Answers validated by Pydantic (automatic — before this function runs)
    2. Infrastructure mapped by Python (deterministic)
    3. Brief generated by Gemini (structured JSON)
    4. Brief validated by Pydantic (catches vague language)
    5. PDF rendered by ReportLab (professional output)
    6. Download token signed by itsdangerous (60-min expiry)
    """
    logger.info("Brief generation request received")

    try:
        # Step 1-4: Generate and validate the brief
        # (infrastructure mapping and Gemini call happen inside generate_brief)
        brief = await generate_brief(answers)

        # Extract organisation name for the PDF cover
        org_name = extract_organisation_name(answers.organisation_and_bottleneck)

        # Step 5: Generate PDF (CPU-bound — offload to thread pool)
        filename, pdf_bytes = await run_in_threadpool(
            generate_pdf,
            brief,
            org_name,
            answers.model_dump(),
        )

        # Save PDF to disk
        await run_in_threadpool(save_pdf, filename, pdf_bytes)

        # Step 6: Generate pre-signed download URL
        token = generate_download_token(filename)
        pdf_url = f"{settings.BASE_URL}/download/{token}"

        # Schedule cleanup of old PDFs (non-blocking)
        background_tasks.add_task(cleanup_old_pdfs, max_age_hours=2)

        # Build the API response
        response = APIBriefResponse(
            executive_summary=brief.executive_summary,
            opportunities=brief.opportunities,
            recommended_first_step=brief.recommended_first_step,
            organisation_name=org_name,
            pdf_url=pdf_url,
        )

        logger.info(f"Brief generated successfully for: {org_name}")
        return response

    except ValueError as e:
        logger.error(f"Brief generation failed: {e}")
        raise HTTPException(
            status_code=500,
            detail={
                "error": "brief_generation_failed",
                "message": str(e),
                "recovery": "Please try again. If the issue persists, the AI service may be temporarily unavailable.",
            },
        )
    except Exception as e:
        logger.error(f"Unexpected error in brief generation: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail={
                "error": "internal_error",
                "message": "An unexpected error occurred. Our team has been notified.",
                "recovery": "Please try again in a moment.",
            },
        )


# ═══════════════════════════════════════════════
# GET /download/{token} — PDF download
# ═══════════════════════════════════════════════

@router.get(
    "/download/{token}",
    summary="Download a generated PDF brief",
    description=(
        "Downloads a previously generated PDF brief. "
        "Links are valid for 60 minutes after generation."
    ),
    responses={
        200: {"description": "PDF file download", "content": {"application/pdf": {}}},
        400: {"description": "Invalid download link"},
        404: {"description": "PDF file not found"},
        410: {"description": "Download link has expired"},
    },
)
async def download_brief(token: str):
    """
    Verify the download token and serve the PDF.

    The token contains:
    - The filename (signed, not guessable)
    - A timestamp (checked against PDF_EXPIRY_MINUTES)

    If expired → HTTP 410 (Gone) with a helpful message
    If invalid → HTTP 400
    If file missing → HTTP 404 (cleanup may have removed it)
    """
    try:
        filename = verify_download_token(token)
    except SignatureExpired:
        raise HTTPException(
            status_code=410,
            detail={
                "error": "link_expired",
                "message": (
                    f"This download link has expired. Brief links are valid for "
                    f"{settings.PDF_EXPIRY_MINUTES} minutes. Please generate a new brief."
                ),
            },
        )
    except BadSignature:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "invalid_link",
                "message": "This download link is invalid or has been tampered with.",
            },
        )

    file_path = BRIEFS_DIR / filename

    # Security: prevent directory traversal attacks
    if not file_path.resolve().is_relative_to(BRIEFS_DIR.resolve()):
        raise HTTPException(status_code=400, detail="Invalid file path")

    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail={
                "error": "file_not_found",
                "message": "This brief file is no longer available. It may have been cleaned up.",
                "recovery": "Please generate a new brief.",
            },
        )

    return FileResponse(
        path=file_path,
        filename="ScotlandAI_Opportunity_Brief.pdf",
        media_type="application/pdf",
    )


# ═══════════════════════════════════════════════
# GET /health — Health check
# ═══════════════════════════════════════════════

@router.get(
    "/health",
    summary="Health check",
    description="Returns the service status. Used by Render for health monitoring.",
)
async def health_check():
    """Simple health check — Render pings this to know the service is alive."""
    return {
        "status": "healthy",
        "service": "scotland-ai-navigator",
        "version": "1.0.0",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# ═══════════════════════════════════════════════
# Background Tasks
# ═══════════════════════════════════════════════

def cleanup_old_pdfs(max_age_hours: int = 2):
    """
    Remove PDFs older than max_age_hours.
    Runs as a background task after each brief generation.

    This keeps the server's disk clean without needing a cron job.
    Since the download tokens expire after 60 minutes anyway,
    the files are useless after that point.
    """
    import time
    cutoff = time.time() - (max_age_hours * 3600)
    cleaned = 0

    for pdf_file in BRIEFS_DIR.glob("brief_*.pdf"):
        if pdf_file.stat().st_mtime < cutoff:
            pdf_file.unlink()
            cleaned += 1

    if cleaned > 0:
        logger.info(f"Cleaned up {cleaned} old PDF files")
